[package]
name = "fourinarow-server"
version = "0.7.0"
authors = ["Filippo Orrù <filippoorru@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0.0"
actix = "0.9.0"
actix-web = {version = "2.0.0", features = ["rustls"] }
actix-web-actors = "2.0.0"
actix-files = "0.2.1"
actix-service = "1.0.5"
actix-cors = "0.2.0"
tokio = "0.2.14"

base64 = "0.12.1"
async-std = "1.5.0"
serde = "*"
serde_json = "*"
csv = "1.1.3"
rustls = "0.16"
env_logger = "0.7.1"
rand = "0.7.3"
futures = "0.3.2"
sha3 = "0.8.2"
